Use cmake for installation [REVPI-3011]
RevolutionPi/revpi-repo pull request #8
Opened 2023-02-27 12:04 UTC by nbuchwitz

2023-03-03 07:38 UTC, naruxde approved these changes

2023-03-03 08:05 UTC, iluminat23 requested changes
Use GnuInstallDirs. take a look at this commit:
https://github.com/RevolutionPi/revpi-tools/commit/5e13f50ae728a8a2d52efe33e9fe52f91b18589f

2023-03-03 08:08 UTC, naruxde commented
💡 Right! Things like ${SYSCONFDIR} instead of "/etc/...", right?

https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

2023-03-04 08:49 UTC, naruxde approved these changes

2023-03-06 08:56 UTC, iluminat23 approved these changes

2023-03-07 07:34 UTC, merged